### ISSUE TITLE
History

### ISSUE THREAD

**Issue by yaxarat** [vcu-cmsc355-f17/android-app-triumph#6]
Assigned user story that needs to be implemented. See the first iteration issue for more details.

**Comment by colinjb26** [comment]
As a user I would like to be able to view each tenant’s payment history.
	I would like to see their name, amount paid, and date of the payment.

I would like to be able to monitor payments and who paid them.
	Given that I am on the Rent History page
	I would like to be able to see who has paid for each entry.

I would like to see how much was paid for each payment.
	Given that I am on the Rent History page
	I would like to see who has paid in each entry.

I would like to see how much was paid for each payment.
	Given that I am on the Rent History page
	I would like to see how much was paid in each payment.

**Comment by yaxarat** [comment]
will be taken over by Ali
